# Generated by Django 4.2.16 on 2024-09-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defautl-image/default.png', null=True, upload_to='users_thumbnail'),
        ),
    ]
