# Generated by Django 4.2.16 on 2024-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_userprofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(default='default_image/default.png', upload_to='users_thumbnail'),
        ),
    ]
