# Generated by Django 4.2.16 on 2024-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_userprofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(default='users_thumbnail/images.png', upload_to='users_thumbnail'),
        ),
    ]
