# Generated by Django 4.2.16 on 2024-09-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_userprofile_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
